### ISSUE TITLE
Question about the performance on SIDD dataset

### ISSUE THREAD

**Issue by alwaysuu** [zhengdharia/LUD-VAE#1]
Hi, thanks so much for sharing the source code first! I tested the provided pre-trained model on SIDD validation dataset and only get  34.43/0.851 (PSNR/SSIM) on average. I am wondering if my versions of python and pytorch match yours. I am using python 3.9 and pytorch 1.10.0

**Comment by zhengdihan** [comment]
Hi, I have checked the pre-trained model (DnCNN-LUDVAE-SIDD.pth), and the result is 
![image](https://user-images.githubusercontent.com/78472184/219854917-9204c5dc-faf7-4a63-8663-dc2db29b6090.png)
I am using python 3.8.3 and pytorch 1.6.0
Can you try again and use the pre-trained model DnCNN-LUDVAE-SIDD.pth from https://drive.google.com/drive/folders/1XKIt5WBPh0Fc3AFEcWxZphfs_N_5YnYw
and the code from 
https://github.com/zhengdharia/LUD-VAE/tree/main/LUD_VAE_sidd/DnCNN

**Comment by alwaysuu** [comment]
Thanks for the reply and kind reminder. It seems that I misused the test code. The result now is the same as yours.
